services:
    sveltekit:
        build: .
        ports:
            - '80:8080'
            - '443:8080'
        container_name: sveltekit
        environment:
            - PORT=8080
        depends_on:
            - pocketbase
            - iaserver
        networks:
            - babelNetwork

    pocketbase:
        build: ./db
        # image: ghcr.io/muchobien/pocketbase:latest # wait for official pocketbase image
        restart: unless-stopped
        ports:
            - 8090:8090
        volumes:
            - pocketbase-data:/pb_data
        networks:
            - babelNetwork
        container_name: pocketbase
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
            interval: 60s
            timeout: 5s
            retries: 5

    iaserver:
        build: ./ia_server
        ports:
            - 8000:8000
        networks:
            - babelNetwork
        container_name: iaserver

volumes:
    pocketbase-data:

networks:
    babelNetwork:
        driver: bridge
