services:
    server:
        build: .
        ports:
            - '80:8080'
            - '443:8080'
        environment:
            - NODE_ENV=production
            - PORT=8080
        depends_on:
            - pocketbase
        networks:
            - babelNetwork

    pocketbase:
        image: ghcr.io/muchobien/pocketbase:latest # wait for official pocketbase image
        restart: unless-stopped
        ports:
            - 8090:8090
        volumes:
            - pocketbase-data:/pb_data
        networks:
            - babelNetwork
        container_name: pocketbase
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
            interval: 60s
            timeout: 5s
            retries: 5

volumes:
    pocketbase-data:

networks:
    babelNetwork:
        driver: bridge
