services:
    sveltekit:
        build: .
        container_name: sveltekit_c
        ports:
            - '127.0.0.1:8080:8080'

    iaserver:
        build: ./ia_server
        container_name: iaserver_c
        environment:
            - DB_URL=http://pocketbase:8090
            - PB_BOT_EMAIL=${PB_BOT_EMAIL}
            - PB_BOT_PASSWORD=${PB_BOT_PASSWORD}
            - MISTRAL_API_KEY=${MISTRAL_API_KEY}
            - MISTRAL_MODEL=mistral-small-latest
        depends_on:
            - pocketbase
        volumes:
            - ia-server-data:/data
        restart: unless-stopped

    pocketbase:
        build: ./db
        container_name: pocketbase_c
        ports:
            - '127.0.0.1:8090:8090'
        volumes:
            - pocketbase-data:/pb_data

volumes:
    pocketbase-data:
    pocketbase-migration:
    ia-server-data:
